/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package psl;

import picocli.CommandLine;

public class App {
    public static void main(String[] args) {
        var commandLine = new CommandLine(new Split());
        int exitCode = commandLine.execute(args);
        System.exit(exitCode);
    }
}
